/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  AssemblyProxyBeta,
  AssemblyProxyBetaInterface,
} from "./AssemblyProxyBeta";
import { EthereumException } from '../Exception/EthereumException';

const _abi = [
  {
    inputs: [
      {
        internalType: "enum AssemblyProxyBetaDummy.AdminFuctionGetType",
        name: "func",
        type: "uint8",
      },
    ],
    name: "adminFunctionsGet",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "enum AssemblyProxyBetaDummy.AdminFuctionPutType",
        name: "func",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "parameter",
        type: "address",
      },
    ],
    name: "adminFunctionsPut",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "<$BYTECODE>"

export class AssemblyProxyBeta__factory extends ContractFactory {
  constructor(admin: string, implementation: string, signer?: Signer) {
    let cAdmin = admin.startsWith("0x") ? admin.substring(2) : admin;
    let cImplementation = implementation.startsWith("0x") ? implementation.substring(2) : implementation;

    if(!/^[0-9a-fA-F]+$/.test(cAdmin)){
      throw new EthereumException("ADMIN IS NOT A VALID HEX NUMBER");
    }

    if(cAdmin.length > 64 ){
      throw new EthereumException("ADMIN HAS WRONG LENGTH SHOULD BE 64 (32 BYTES) FOUND: " + cAdmin.length);
    }

    if(!/^[0-9a-fA-F]+$/.test(cImplementation)){
      throw new EthereumException("IMPLEMENTATION IS NOT A VALID HEX NUMBER");
    }

    if(cImplementation.length > 64){
      throw new EthereumException("IMPLEMENTATION HAS WRONG LENGTH SHOULD BE 64 (32 BYTES) FOUND: " + cImplementation.length);
    }

    if(cAdmin.length !==64){
      cAdmin = '0'.repeat(64-cAdmin.length) + cAdmin;
    }

    if(cImplementation.length !==64){
      cImplementation = '0'.repeat(64-cImplementation.length) + cImplementation;
    }

    const buffCode = Buffer.from(_bytecode);
    const adminCode = Buffer.from(cAdmin);
    const implementationCode = Buffer.from(cImplementation);
    adminCode.copy(buffCode,"<$INITIAL_ADMIN_DIR>"*2+2);
    implementationCode.copy(buffCode,"<$INITIAL_IMPLEMENTATION_DIR>"*2+2);
    super(_abi, buffCode.toString(), signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<AssemblyProxyBeta> {
    return super.deploy(overrides || {}) as Promise<AssemblyProxyBeta>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): AssemblyProxyBeta {
    return super.attach(address) as AssemblyProxyBeta;
  }
  connect(signer: Signer): AssemblyProxyBeta__factory {
    return super.connect(signer) as AssemblyProxyBeta__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AssemblyProxyBetaInterface {
    return new utils.Interface(_abi) as AssemblyProxyBetaInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AssemblyProxyBeta {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as AssemblyProxyBeta;
  }
}
