/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface AssemblyProxyBetaInterface extends ethers.utils.Interface {
  functions: {
    "adminFunctionsGet(uint8)": FunctionFragment;
    "adminFunctionsPut(uint8,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "adminFunctionsGet",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "adminFunctionsPut",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "adminFunctionsGet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminFunctionsPut",
    data: BytesLike
  ): Result;

  events: {};
}

export class AssemblyProxyBeta extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: AssemblyProxyBetaInterface;

  functions: {
    adminFunctionsGet(
      func: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    adminFunctionsPut(
      func: BigNumberish,
      parameter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  adminFunctionsGet(
    func: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  adminFunctionsPut(
    func: BigNumberish,
    parameter: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    adminFunctionsGet(
      func: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    adminFunctionsPut(
      func: BigNumberish,
      parameter: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    adminFunctionsGet(
      func: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    adminFunctionsPut(
      func: BigNumberish,
      parameter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    adminFunctionsGet(
      func: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    adminFunctionsPut(
      func: BigNumberish,
      parameter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
