/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
  type Signer,
  type ContractDeployTransaction,
  type ContractRunner
} from "ethers";
import type {  } from "ethers";
import type { NonPayableOverrides } from "../typechain/common";
import type {
  AssemblyProxyBeta,
  AssemblyProxyBetaInterface,
} from "../typechain/contracts/AssemblyProxyBeta";

import { EthereumException } from '../Exception/EthereumException'

const _abi = [
  {
    inputs: [],
    name: "implementation",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "enum AssemblyProxyBeta.AdminFuctionPutType",
        name: "func",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "parameter",
        type: "address",
      },
    ],
    name: "adminFunctionsPut",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "implementation",
        type: "address",
      },
    ],
    name: "Upgraded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "previousAdmin",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "newAdmin",
        type: "address",
      },
    ],
    name: "AdminChanged",
    type: "event",
  }
];

const _bytecode =
  "0x7F00000000000000000000000000000000000000000000000000000000000000007FFFFFFFFFFFFFFFFFFFFFFFFFDCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD557F0000000000000000000000000000000000000000000000000000000000000000803B6100F95760846000816100B18239FD08C379A00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002D455243313936373A206E657720696D706C656D656E746174696F6E206973206E6F74206120636F6E7472616374000000000000000000000000000000000000005B7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFDCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE5561029D6000816101288239F336604F575B610000368180378036817FFFFFFFFFFFFFFFFFFFFFFFFFFFFFDCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE545AF4603F573D6000803E3D6000FD5B3D604557005B3D6000803E3D6000F35B60003560E01C80635C60DA1B146101D65763C488FE3B036004577FFFFFFFFFFFFFFFFFFFFFFFFFDCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD5433036004573461022D5760043561017F57602435803B6101355760846000816100B18239FD08C379A00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002D455243313936373A206E657720696D706C656D656E746174696F6E206973206E6F74206120636F6E7472616374000000000000000000000000000000000000005B807FFFFFFFFFFFFFFFFFFFFFFFFFFFFFDCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE557FBC7CD75A20EE27FD9ADEBAB32041F755214DBC6BFFA90CC0225B39DA2E5C2D3B600080A2005B6024358060205233600052807FFFFFFFFFFFFFFFFFFFFFFFFFDCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD55337F7E644D79422F17C01E4894B5F4F588D331EBFA28653D42AE832DC59E38C9798F60406000A3005B7FFFFFFFFFFFFFFFFFFFFFFFFFDCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD5433036004573461022D577FFFFFFFFFFFFFFFFFFFFFFFFFFFFFDCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE5460005260206000F35B60646000816102398239FD08C379A0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000134E4F54205041594D454E5420414C4C4F57454400000000000000000000000000"

export class AssemblyProxyBeta__factory extends ContractFactory {
  constructor(admin: string, implementation: string, signer?: Signer) {
    let cAdmin = admin.startsWith("0x") ? admin.substring(2) : admin;
    let cImplementation = implementation.startsWith("0x") ? implementation.substring(2) : implementation;

    if(!/^[0-9a-fA-F]+$/.test(cAdmin)){
      throw new EthereumException("ADMIN IS NOT A VALID HEX NUMBER");
    }

    if(cAdmin.length > 64 ){
      throw new EthereumException("ADMIN HAS WRONG LENGTH SHOULD BE 64 (32 BYTES) FOUND: " + cAdmin.length);
    }

    if(!/^[0-9a-fA-F]+$/.test(cImplementation)){
      throw new EthereumException("IMPLEMENTATION IS NOT A VALID HEX NUMBER");
    }

    if(cImplementation.length > 64){
      throw new EthereumException("IMPLEMENTATION HAS WRONG LENGTH SHOULD BE 64 (32 BYTES) FOUND: " + cImplementation.length);
    }

    if(cAdmin.length !==64){
      cAdmin = '0'.repeat(64-cAdmin.length) + cAdmin;
    }

    if(cImplementation.length !==64){
      cImplementation = '0'.repeat(64-cImplementation.length) + cImplementation;
    }

    const buffCode = Buffer.from(_bytecode);
    const adminCode = Buffer.from(cAdmin);
    const implementationCode = Buffer.from(cImplementation);
    adminCode.copy(buffCode,[1][0]*2 + 2);
    implementationCode.copy(buffCode,[68][0]*2 + 2);
    super(_abi, buffCode.toString(), signer);
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      AssemblyProxyBeta & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): AssemblyProxyBeta__factory {
    return super.connect(runner) as AssemblyProxyBeta__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AssemblyProxyBetaInterface {
    return new Interface(_abi) as AssemblyProxyBetaInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AssemblyProxyBeta {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as AssemblyProxyBeta;
  }
}